### ISSUE TITLE
Selecting another Bible version causes error

### ISSUE THREAD

**Issue by timbze** [bobeaton/OneStoryEditor#6]
In the Bible translation selection window, uncheck "NET", and check "KJV" and then click OK. Error below comes up.
![image](https://user-images.githubusercontent.com/35117769/125643329-2818b2e6-288b-4e9b-aca7-4356615bdcb2.png)

```
Msg: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Class: System.ArgumentOutOfRangeException
Source: mscorlib
Assembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at OneStoryProjectEditor.ViewSwordOptionsForm.buttonOK_Click(Object sender, EventArgs e) in C:\Users\pete_\source\repos\OneStoryEditor\StoryEditor\ViewSwordOptionsForm.cs:line 211
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Thread: 
Thread UI culture: en-US
Exception: System.ArgumentOutOfRangeException

--Error Reporting Properties--
Version: Version 5.0.0 (apparent build date: 24-May-2021)
CommandLine: "C:\Program Files (x86)\SIL\OneStory Editor\StoryEditor.exe" 
CurrentDirectory: C:\Program Files (x86)\SIL\OneStory Editor
MachineName: DESKTOP-ORSCUOI
OSVersion: Windows 10 
DotNetVersion: 4.8.04084 (528372)
CLR Version (deprecated): 4.0.30319.42000
WorkingSet: 25309184
UserDomainName: DESKTOP-ORSCUOI
UserName: Timmy
Culture: en-US
KeyboardAdaptors: WinKeyboardAdaptor

--Log--
Wednesday, July 14, 2021
8:49:31	App Launched with ["C:\Program Files (x86)\SIL\OneStory Editor\StoryEditor.exe" ]
8:49:32	Keyboard adaptors in use: WinKeyboardAdaptor
8:49:43	Exception: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Details of most recent events:
8:49:31	App Launched with ["C:\Program Files (x86)\SIL\OneStory Editor\StoryEditor.exe" ]
8:49:32	Keyboard adaptors in use: WinKeyboardAdaptor
8:49:43	Exception: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

```

**Comment by venukommu** [comment]
Dear @timbze 
We have already fixed this issue while ago. You can one more trick here after download exe folder from SIL and another msi from Dropbox, replace the exe file in the folder from SIL with the msi file that you have downloaded from Dropbox. This issue can be resolved by latest msi file since we fixed it already there. Meanwhile i'll double check what version was deployed to SIL website either latest or bit old one.

**Comment by bobeaton** [comment]
Hi Venu,

I think I referred Timmy to the installer from the NewWixInstaller branch, so it’s possible that the fix you mentioned isn’t in there…

That said, I wasn’t able to work out what the problem was from the stack trace. Do you know what it was? (that code has changed significantly in the NewWixInstaller branch, bkz it now has a totally new version of the SWORD resources, which Timmy was reviewing).

OR, Timmy, if you could give more details about what you did that caused that exception…

I couldn’t find any version of the source code within the last decade for which this line even has code on it:


C:\Users\pete_\source\repos\OneStoryEditor\StoryEditor\ViewSwordOptionsForm.cs:line 211

Bob
